<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AxisLink.Core\AxisLink.Core.csproj" />
		<ProjectReference Include="..\AxisLink.Infrastructure\AxisLink.Infrastructure.csproj" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Dock.Avalonia" Version="12.0.0.2" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="12.0.0.2" />
    <PackageReference Include="Dock.Model.Avalonia" Version="12.0.0.2" />
    <PackageReference Include="Dock.Model.Mvvm" Version="12.0.0.2" />
    <PackageReference Include="Dock.Serializer.Xml" Version="12.0.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
    <PackageReference Include="TreeDataGrid" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Windows\ControllerCommunication\" />
    <Folder Include="Views\Windows\GroupsWindow\" />
    <Folder Include="Views\Windows\PatchWindow\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Windows\SensorWindow\SensorWindow.axaml.cs">
      <DependentUpon>SensorWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
